on:
  schedule:
    # runs once a day
    - cron: "05 22 * * *"
    
jobs:
  zenodo_stats:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Check out NMRLipids/Databank
      uses: actions/checkout@v2
      with:
        repository: NMRLipids/Databank
        path: NMRLipidsDB
    
    # Get zenodo DOIs and query stats from API
    - name: Zenodo stats
      run: |
        .github/workflow/zenodo_stats.sh
    # Commits files to repository
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: GitHub action
        message: "GitHub traffic"
        add: "./traffic/*"
